#!/usr/bin/env python3
"""
Convert web/sprites.json -> firmware/serial_avatar/sprites.h

Each sprite becomes a PROGMEM array of UTF-8 strings (one per frame).
A compile-time lookup table maps spriteKey (e.g. "male_0_2smile") to
(frame_count, frame_pointers).

Usage:
    python3 scripts/sprites_to_header.py
"""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITES_JSON = ROOT / "web" / "sprites.json"
HEADER_OUT = ROOT / "firmware" / "serial_avatar" / "sprites.h"


def c_escape_utf8(s: str) -> str:
    """Escape a UTF-8 Python string for a C string literal.
    Non-ASCII bytes are emitted as \\xNN escapes — portable across compilers,
    avoids source-encoding surprises.

    Tricky detail: C11 §6.4.4.4 says \\xHH... is *greedy* — it consumes as
    many hex digits as follow it. So "\\xe2\\x86" followed by "00" collapses
    into a single \\x8600 escape (→ truncated to 0x00, silently terminating
    the string). We defuse that by splitting the string literal every time
    a hex escape is followed by a character that is a valid hex digit
    (0-9, a-f, A-F) — the adjacent "" concatenation keeps the value
    identical while forcing the compiler to end the escape.
    """
    HEX_CHARS = set("0123456789abcdefABCDEF")
    out = []
    last_was_hex_escape = False
    for b in s.encode("utf-8"):
        ch = chr(b) if 0x20 <= b < 0x7F else ""
        # If previous emit was \xNN and this char would extend the escape,
        # break the string literal so the compiler stops consuming hex.
        if last_was_hex_escape and ch and ch in HEX_CHARS:
            out.append('" "')
        if b == 0x22:
            out.append("\\\"")
            last_was_hex_escape = False
        elif b == 0x5C:
            out.append("\\\\")
            last_was_hex_escape = False
        elif b == 0x0A:
            out.append("\\n")
            last_was_hex_escape = False
        elif b == 0x09:
            out.append("\\t")
            last_was_hex_escape = False
        elif 0x20 <= b < 0x7F:
            out.append(ch)
            last_was_hex_escape = False
        else:
            out.append(f"\\x{b:02x}")
            last_was_hex_escape = True
    return "".join(out)


def sprite_ident(key: str) -> str:
    """Make a valid C identifier from a sprite key like 'male_3_1smile'."""
    return "spr_" + key.replace("-", "_")


def main() -> None:
    with open(SPRITES_JSON, encoding="utf-8") as f:
        data = json.load(f)

    # Filter to actual sprites (skip metadata keys if any)
    sprites = {
        k: v for k, v in data.items()
        if isinstance(v, list) and v and isinstance(v[0], str)
    }

    if not sprites:
        raise SystemExit("No sprites found in sprites.json")

    lines: list[str] = []
    lines.append("// GENERATED by scripts/sprites_to_header.py — DO NOT EDIT by hand.")
    lines.append("// Source: web/sprites.json (hello-stranger, MIT, The Pudding 2022).")
    lines.append("// Each sprite = N frames of UTF-8 text (18 rows × 18 cols).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Opt-in to U8g2's large Unicode BMP fonts (guarded in each font header).")
    lines.append("// Must be defined before Arduino_GFX pulls in the font headers, so this")
    lines.append("// file is deliberately the first include in the sketch.")
    lines.append("#ifndef U8G2_USE_LARGE_FONTS")
    lines.append("#define U8G2_USE_LARGE_FONTS")
    lines.append("#endif")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")

    # Emit frame strings
    for key in sorted(sprites.keys()):
        frames = sprites[key]
        ident = sprite_ident(key)
        for i, frame in enumerate(frames):
            lines.append(
                f'static const char {ident}_f{i}[] PROGMEM = "{c_escape_utf8(frame)}";'
            )
        # Array of frame pointers
        arr = ", ".join(f"{ident}_f{i}" for i in range(len(frames)))
        lines.append(f"static const char* const {ident}_frames[] PROGMEM = {{ {arr} }};")
        lines.append("")

    # Dispatch table
    lines.append("struct SpriteEntry {")
    lines.append("  const char*         key;           // e.g. \"male_0_2smile\"")
    lines.append("  uint8_t             frame_count;")
    lines.append("  const char* const*  frames;        // PROGMEM array of PROGMEM strings")
    lines.append("};")
    lines.append("")
    lines.append("static const SpriteEntry SPRITES[] = {")
    for key in sorted(sprites.keys()):
        ident = sprite_ident(key)
        n = len(sprites[key])
        lines.append(f'  {{ "{key}", {n}, {ident}_frames }},')
    lines.append("};")
    lines.append(f"static const uint16_t SPRITES_COUNT = {len(sprites)};")
    lines.append("")

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    HEADER_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    total_bytes = sum(
        sum(len(f.encode("utf-8")) for f in frames) for frames in sprites.values()
    )
    print(f"wrote {HEADER_OUT}")
    print(f"  {len(sprites)} sprites, {total_bytes} bytes of UTF-8 sprite data")


if __name__ == "__main__":
    main()
